name: ue datu cottages
favicon: null
layout_spectrum: 0.9991
typography_spectrum: 0.00271
title: 'Lake poso, saloupa waterfall, syuri beach and around Tentena'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
