analytics: {}
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.188003
  lightness: 0.441367
  rhythmicContrast: 0.229635
  saturation: 0.032349
cta: {}
layout_spectrum: 0.250642
name: uedatucottages.com
opengraph: {}
purpose: []
typography_spectrum: 0.188926
