name: uedatucottages.com
favicon: null
layout_spectrum: 0.2506420072168112
typography_spectrum: 0.18892679479904473
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.1880039838142693
  lightness: 0.44136756006628275
  saturation: 0.032349092653021216
  rhythmicContrast: 0.2296350672841072
purpose: []
