name: uedatucottages.com
favicon: null
layout_spectrum: 0.250642
typography_spectrum: 0.188926
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.188003
  lightness: 0.441367
  saturation: 0.032349
  rhythmicContrast: 0.229635
purpose: []
